[development]
dynaconf_merge = true

[development.security]
# openssl rand -hex 32
SECRET_KEY = "9638106511f9cdc7ee5c9694edb222ea42cf5e6ae3c7a490cac831828409cb83"
RESET_TOKEN_EXPIRE_MINUTES = 10
PWD_RESET_URL = "https://dm.com/reset_password"

[default.email]
debug_mode = true
smtp_sender = "no-reply@dm.com"
smtp_server = "localhost"
smtp_port = 1025
smtp_user = "<replace in .secrets.toml>"
smtp_password = "<replace in .secrets.toml>"
